# ==========================================================
# CloudFormation - EC2
# ==========================================================

EC2_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 Instance

Resources:

  EC2Instance:

    Type: AWS::EC2::Instance

    Properties:

      InstanceType: {instance_type}

      ImageId: {ami_id}

      Tags:

        - Key: Name

          Value: {resource_name}
"""


# ==========================================================
# CloudFormation - S3
# ==========================================================

S3_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Resources:

  S3Bucket:

    Type: AWS::S3::Bucket

    Properties:

      BucketName: {bucket_name}
"""


# ==========================================================
# CloudFormation - VPC
# ==========================================================

VPC_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Resources:

  VPC:

    Type: AWS::EC2::VPC

    Properties:

      CidrBlock: {vpc_cidr}

      Tags:

        - Key: Name

          Value: {resource_name}
"""


# ==========================================================
# CloudFormation - IAM Role
# ==========================================================

IAM_ROLE_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Resources:

  IAMRole:

    Type: AWS::IAM::Role

    Properties:

      RoleName: {iam_role_name}

      AssumeRolePolicyDocument:

        Version: '2012-10-17'

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - ec2.amazonaws.com

            Action:

              - sts:AssumeRole
"""


# ==========================================================
# CloudFormation - Lambda
# ==========================================================

LAMBDA_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Resources:

  LambdaFunction:

    Type: AWS::Lambda::Function

    Properties:

      FunctionName: {resource_name}

      Runtime: {lambda_runtime}

      Handler: {lambda_handler}

      Role: arn:aws:iam::123456789012:role/{iam_role_name}

      Code:

        ZipFile: |

          def lambda_handler(event, context):

              return {{
                  "statusCode": 200
              }}
"""


# ==========================================================
# CloudFormation - RDS
# ==========================================================

RDS_CLOUDFORMATION = """AWSTemplateFormatVersion: '2010-09-09'

Resources:

  Database:

    Type: AWS::RDS::DBInstance

    Properties:

      DBInstanceClass: db.t3.micro

      Engine: {database_engine}

      AllocatedStorage: 20
"""


# ==========================================================
# AWS CLI
# ==========================================================

AWS_CLI = """#!/bin/bash

aws configure

echo "Deploying {resource_name}..."

echo "Region: {region}"
"""


# ==========================================================
# IAM Policy
# ==========================================================

IAM_POLICY = """{{
  "Version": "2012-10-17",
  "Statement": [
    {{
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }}
  ]
}}
"""


# ==========================================================
# Architecture
# ==========================================================

ARCHITECTURE = """# AWS Architecture

Service: {service}

Resource Name: {resource_name}

Region: {region}

Generated by OpsNova AI.
"""