# ==========================================================
# Jenkinsfile
# ==========================================================

JENKINSFILE = """pipeline {{

    agent any

    stages {{

        stage('Checkout') {{
            steps {{
                checkout scm
            }}
        }}

        stage('Build') {{
            steps {{
                echo 'Building {pipeline_name}'
            }}
        }}

        stage('Test') {{
            steps {{
                echo 'Running Tests'
            }}
        }}

        stage('Docker Build') {{
            steps {{
                sh 'docker build -t {docker_image} .'
            }}
        }}

        stage('Deploy') {{
            steps {{
                echo 'Deploying to {deployment_target}'
            }}
        }}

    }}

}}
"""

# ==========================================================
# GitHub Actions Workflow
# ==========================================================

GITHUB_ACTIONS = """name: {pipeline_name}

on:

  push:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build

        run: echo "Building..."

      - name: Test

        run: echo "Testing..."

      - name: Docker Build

        run: docker build -t {docker_image} .
"""

# ==========================================================
# README
# ==========================================================

README = """# {pipeline_name}

## CI/CD Pipeline

Technology Stack

- Language: {language}
- Framework: {framework}
- CI Tool: {ci_tool}
- Cloud: {cloud_provider}
- Registry: {registry}
- Deployment: {deployment_target}

Generated by OpsNova AI
"""

# ==========================================================
# Pipeline Diagram
# ==========================================================

PIPELINE_DIAGRAM = """Developer

↓

GitHub Repository

↓

{ci_tool}

↓

Build

↓

Test

↓

Docker Build

↓

Push Image

↓

Terraform

↓

Ansible

↓

Kubernetes

↓

{cloud_provider}
"""