# ==========================================================
# USER MANAGEMENT
# ==========================================================

USER_COMMANDS = """# User Management

sudo useradd {username}

sudo passwd {username}

sudo groupadd {group_name}

sudo usermod -aG {group_name} {username}

id {username}
"""

USER_AUTOMATION = """#!/bin/bash

echo "Creating User..."

sudo useradd {username}

sudo passwd {username}

sudo groupadd {group_name}

sudo usermod -aG {group_name} {username}

echo "Completed"
"""

# ==========================================================
# FILE MANAGEMENT
# ==========================================================

FILE_COMMANDS = """# File Management

cp {source_path} {destination_path}

mv {source_path} {destination_path}

rm -rf {source_path}

mkdir -p {directory_name}

find / -name "*.log"
"""

FILE_AUTOMATION = """#!/bin/bash

mkdir -p {directory_name}

cp {source_path} {destination_path}

echo "Files copied successfully."
"""

# ==========================================================
# PERMISSIONS
# ==========================================================

PERMISSION_COMMANDS = """# File Permissions

chmod 755 {directory_name}

chown {username}:{group_name} {directory_name}

ls -l {directory_name}
"""

PERMISSION_AUTOMATION = """#!/bin/bash

sudo chmod -R 755 {directory_name}

sudo chown -R {username}:{group_name} {directory_name}

echo "Permissions updated."
"""

# ==========================================================
# PACKAGE MANAGEMENT
# ==========================================================

PACKAGE_COMMANDS = """# Package Installation

sudo apt update

sudo apt install -y {package_name}

sudo apt remove -y {package_name}
"""

PACKAGE_AUTOMATION = """#!/bin/bash

sudo apt update

sudo apt install -y {package_name}

echo "{package_name} installed."
"""

# ==========================================================
# NETWORKING
# ==========================================================

NETWORK_COMMANDS = """# Networking

ping google.com

curl https://google.com

wget https://example.com/file.zip

ip addr show {network_interface}

ss -tulpn
"""

NETWORK_AUTOMATION = """#!/bin/bash

echo "Checking Network..."

ping -c 4 google.com

ip addr

ss -tulpn
"""

# ==========================================================
# PROCESS MANAGEMENT
# ==========================================================

PROCESS_COMMANDS = """# Process Management

ps -ef

top

killall {process_name}

jobs
"""

PROCESS_AUTOMATION = """#!/bin/bash

echo "Stopping {process_name}"

sudo killall {process_name}
"""

# ==========================================================
# SERVICE MANAGEMENT
# ==========================================================

SERVICE_COMMANDS = """# Services

sudo systemctl start {service_name}

sudo systemctl stop {service_name}

sudo systemctl restart {service_name}

sudo systemctl status {service_name}
"""

SERVICE_AUTOMATION = """#!/bin/bash

sudo systemctl restart {service_name}

sudo systemctl enable {service_name}

echo "Service restarted."
"""

# ==========================================================
# DISK MANAGEMENT
# ==========================================================

DISK_COMMANDS = """# Disk

df -h

du -sh *

mount

lsblk
"""

DISK_AUTOMATION = """#!/bin/bash

echo "Disk Usage"

df -h

du -sh *
"""

# ==========================================================
# MONITORING
# ==========================================================

MONITOR_COMMANDS = """# Monitoring

top

htop

free -h

vmstat

iostat
"""

MONITOR_AUTOMATION = """#!/bin/bash

echo "System Monitoring"

free -h

top
"""

# ==========================================================
# README
# ==========================================================

README = """# Linux Expert

Category: {category}

Distribution: {distribution}

Generated by OpsNova AI.
"""

# ==========================================================
# CHEAT SHEET
# ==========================================================

CHEATSHEET = """# Linux Cheat Sheet

Common Commands

pwd

ls -la

cd

mkdir

rm

cp

mv

find

grep

chmod

chown

systemctl

journalctl

df -h

free -h

top
"""