export interface DockerConfig {
  appName: string;
  language: string;
  framework: string;
  port: string;
}

export function generateDockerfile(config: DockerConfig): string {
  return `# Dockerfile generated by OpsNova AI

FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

EXPOSE ${config.port}

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","${config.port}"]`;
}